### ISSUE TITLE
When will you release your code?

### ISSUE THREAD

**Issue by YuyingShang** [zhongfansun/HPM#1]
Excuse me, when will you release your code. Waiting forward to you reply!

**Comment by zhongfansun** [comment]
I have been busy with my mentor's project recently. I will try my best to clean up my code and upload it before next month. Thank you for your attention.

**Comment by YuyingShang** [comment]
Thank you for your reply. If it's possible, could you please upload the pre-processed okvqa dataset? I'm curious about how your answer dictionary is built?

**Comment by zhongfansun** [comment]
Sorry for submitting so late. Our code mainly relies on [UniFER](https://github.com/guoyang9/UnifER) and has the same data pre-processed.
